---
- name: Update cache
  apt: 
    update_cache: "True"

- name: Install python
  apt:
    name: python3
    state: latest

- name: Install php
  apt:
    name: php
    state: latest
       
- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract files
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no

- name: Copy sample config
  shell: cp /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php

- name: Update WordPress Config file
  lineinfile:
    dest=/var/www/wordpress/wp-config.php
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - { 'regexp': "define\\('DB_NAME'), '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_postgres_db}}');" }
    - { 'regexp': "define\\('DB_USER'), '(.)+'\\);", 'line': "define('DB_USER', '{{wp_postgres_user}}');" }
    - { 'regexp': "define\\('DB_PASSWORD'), '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_postgres_password}}');" }
