name: AWS Workflow

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        description: "working directory"
        type: string
        required: true
    secrets:
      GCP_EMAIL:
        required: true
      GCP_SA_KEY:
        required: true

env:
  WORKING_DIRECTORY : ${{ inputs.WORKING_DIRECTORY }}

jobs:
  tf_deployment:
  runs_on: ubuntu-latest

  - name: Config credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-2
  - name: Setup Terraform CLI
    uses: hashicorp/setup-terraform@v2.0.2

  - name: Terraform init
    working-directory: gcp
    run: |
      terraform init
      terraform plan
      terraform apply -auto-approve


