name: AWS Workflow

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        description: "working directory"
        type: string
        required: true
    secrets:
      GCP_EMAIL:
        required: true
      GCP_SA_KEY:
        required: true

env:
  WORKING_DIRECTORY : ${{ inputs.WORKING_DIRECTORY }}

jobs:
  tf_deployment:
    runs_on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
