name: GCP Workflow

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        description: "working directory"
        type: string
        required: true
    secrets:
      GCP_EMAIL:
        required: true
      GCP_SA_KEY:
        required: true

env:
  WORKING_DIRECTORY : ${{ inputs.WORKING_DIRECTORY }}

jobs:
  tf_deployment:
    runs_on: ubuntu-latest
    steps:

    - name: Config credentials
      uses: google-github-actions/setup-gcloud@v0
      with:
        aws-access-key-id: ${{ secrets.GCP_EMAIL }}
        aws-secret-access-key: ${{ secrets.GCP_SA_KEY }}
        projecct_id: "My First Project"
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2

    - name: Terraform init
      working-directory: gcp
      run: |
        terraform init
        terraform plan
        terraform apply -auto-approve
