name: GCP Workflow

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        description: "working directory"
        type: string
        required: true
    secrets:
      GCP_EMAIL:
        required: true
      GCP_SA_KEY:
        required: true

env:
  WORKING_DIRECTORY : ${{ inputs.WORKING_DIRECTORY }}

jobs:
  tf_deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform init
      working-directory: gcp
      run: |
        terraform init
        terraform plan
        terraform apply -auto-approve
        terraform destroy -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
