name: GCP Workflow

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        description: "working directory"
        type: string
        required: true
      Endpoint:
        description: "change database endpoint"
        type: string
        required: true
    secrets:
      GCP_EMAIL:
        required: true
      GCP_SA_KEY:
        required: true

env:
  WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
  ENDPOINT: ${{ inputs.ENDPOINT }}

jobs:
  tf_deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set DB Creds
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        sed -ie "s/{__USER__}/${{ secrets.DB_USER }}/g" roles/wordpress/defaults/main.yml
        sed -ie "s/{__PASS__}/${{ secrets.DB_PASS }}/g" roles/wordpress/defaults/main.yml
        echo "${{ secrets.ANSIBLE_KEY }}" > ansible.ssh
    - name: Terraform init
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        terraform init
        terraform plan
        terraform destroy -auto-approve
        #terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
    - name: Verify endpoint var
      run: |
        EP="${{ secrets.DB_USER }}${{ env.ENDPOINT }}"
        echo $EP
