name: Push Workflow

on:
  push:
    branches:
    - main

jobs:
  aws_workflow:
    uses: ./.github/workflows/aws-workflow.yml
    with:
      WORKING_DIRECTORY: "./aws"
    secrets: inherit
  verify_var:
    needs: aws_workflow
    steps:
      run: echo ${{ needs.aws_workflow.outputs.endpoint}}
# gcp_workflow:
#   needs: aws_workflow
#   if: (needs.aws_workflow.result == 'success')
#   uses: ./.github/workflows/gcp-workflow.yml
#   with:
#     WORKING_DIRECTORY: "./gcp"
#     ENDPOINT: "${{ needs.aws_workflow.outputs.endpoint }}"
#   secrets: inherit
