name: Push Workflow

on:
  push:
    branches:
    - main

jobs:
  aws_workflow:
    uses: ./.github/workflows/aws-workflow.yml
    with:
      WORKING_DIRECTORY: "./aws"
    secrets: inherit
  gcp_workflow:
    needs: aws_workflow
    uses: ./.github/workflows/gcp-workflow.yml
    with:
      WORKING_DIRECTORY: "./gcp"
      ENDPOINT: "${{ needs.aws_workflow.outputs.endpoint }}"
    secrets: inherit
