name: Push Workflow

on:
  push:
    branches:
    - main

jobs:
  aws_workflow:
    uses: ./.github/workflows/gcp-workflow.yml
    with:
      WORKING_DIRECTORY: "./aws"
    secrets: inherit
  gcp_workflow:
    uses: ./.github/workflows/gcp-workflow.yml
    with:
      WORKING_DIRECTORY: "./gcp"
    secrets: inherit
